spring.application.name=${SPRING_APP_NAME:aula}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_aula}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
